version: "3"
services:
  web:
    image: wemstar/prezentacja:1.0
    deploy:
      replicas: 5
      update_config:
        delay: 30s
      restart_policy:
        condition: on-failure
    ports:
      - "8999:8080"
    networks:
      - webnet
networks:
  webnet: